Rewrote git-status script

diff --git a/bin/git-status b/bin/git-status
--- a/bin/git-status
+++ b/bin/git-status
@@ -6,51 +6,55 @@
 # Homepage:     https://core23.de
 #
 
-help ()
-{
+help() {
         cat <<EOF 1>&2
 Shows git statistics for multiple projects
 
-Usage: git-status.sh [options] [path]
+Usage: git-status [options] [path]
 
    Options
       -l expects a minimal new commit count
+      -d depth of the scan
       -h help
 
 EOF
         exit 1
 }
 
-function gitLine {
+
+function process-project() {
     if [ ! -d ".git" ]; then
         return
     fi
 
-    NAME=`echo "$1" | tr -d '\/'`
+    NAME=`echo "$1" | tr -d '\.\/'`
+    REMOTE=""
     BRANCH="master"
     TAG=""
     COMMIT_COUNT=0
     COMMIT_TAG_COUNT=0
+    COMMIT_LOCAL_COUNT=0
+
+    # Detect leading remote
+    for R in `git remote | head -1` "origin" "upstream"; do
+        if [[ `git remote | grep $R` && `git branch -r | grep "$R/"` ]]; then
+            REMOTE=$R
+        fi
+    done
 
     # Detect latest tag
-    if [[ `git tag | wc -l  | xargs` > 0 ]]; then
+    if [[ `git tag | wc -l | xargs` > 0 ]]; then
         TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
     fi
 
-    # Check for remote upstream
-    REMOTE="origin"
-    if [[ `git remote | grep upstream` ]]; then
-        REMOTE="upstream"
-    fi
-
     # Detect latest branch based on last tag
-    if [[ $TAG != '' ]]; then
+    if [[ $REMOTE != '' && $TAG != '' ]]; then
         VERSION_PARTS=( ${TAG//./ } )
         VERSIONS=()
 
         if [[ ${#VERSION_PARTS[@]} -gt 2 ]]; then
             VERSIONS+=("${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.x")
-            VERSIONS+=("${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.0")
+            VERSIONS+=("${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.0bash")
             VERSIONS+=("${VERSION_PARTS[0]}.${VERSION_PARTS[1]}")
         fi
         if [[ ${#VERSION_PARTS[@]} -gt 1 ]]; then
@@ -66,62 +70,74 @@ function gitLine {
         done
     fi
 
-    COMMIT_COUNT=`git rev-list $REMOTE/$BRANCH --count`
-    if [[ $TAG != '' ]]; then
+    if [[ $REMOTE != '' && $BRANCH != '' ]]; then
+        COMMIT_COUNT=`git rev-list $REMOTE/$BRANCH --count`
+    fi
+
+    if [[ $REMOTE != '' && $TAG != '' ]]; then
         COMMIT_TAG_COUNT=`git rev-list $TAG..$REMOTE/$BRANCH --count`
     fi
 
+    if [[ $COMMIT_COUNT -gt 0 ]]; then
+        COMMIT_LOCAL_COUNT=`git log --branches --not --remotes --oneline | wc -l`
+    fi
+
+    # Totals
     if [[ $COMMIT_TAG_COUNT -gt $limit ]]; then
         TOTAL_MODULES=$(($TOTAL_MODULES + 1))
         TOTAL_COMMITS=$(($TOTAL_COMMITS + $COMMIT_COUNT))
         TOTAL_CHANGES=$(($TOTAL_CHANGES + $COMMIT_TAG_COUNT))
+        TOTAL_LOCAL=$(($TOTAL_LOCAL + $COMMIT_LOCAL_COUNT))
 
-        printf "$LINE_FORMAT" "$NAME" "$TAG" "$BRANCH" "$COMMIT_COUNT" "$COMMIT_TAG_COUNT"
+        printf "$LINE_FORMAT" "$NAME" "$TAG" "$BRANCH" "$COMMIT_COUNT" "$COMMIT_TAG_COUNT" "$COMMIT_LOCAL_COUNT"
     fi
 }
 
-process () {
-    DIVIDER=`printf '%0.1s' "#"{1..85}`
-    HEADER_FORMAT="\n %-40s %10s %10s %10s %10s\n"
-    FOOTER_FORMAT=" %-40s %10s %10s %10d %10d\n"
-    LINE_FORMAT=" %-40s %10s %10s %10d %10d\n"
+
+process() {
+    DIVIDER=`printf '%0.1s' "#"{1..97}`
+    HEADER_FORMAT="\n %-40s %10s %10s %10s %10s %10s\n"
+    FOOTER_FORMAT=" %-40s %10s %10s %10d %10d %10d\n"
+    LINE_FORMAT=" %-40s %10s %10s %10d %10d %10d\n"
 
     TOTAL_MODULES=0
     TOTAL_COMMITS=0
     TOTAL_CHANGES=0
+    TOTAL_LOCAL=0
 
-    printf "$HEADER_FORMAT" "Bundle" "Version" "Branch" "Commits" "New"
+    printf "$HEADER_FORMAT" "Bundle" "Version" "Branch" "Commits" "Untagged" "Local"
     echo $DIVIDER
 
-    ###################
-    # Start
-    ###################
+    process-project ${PWD##*/}
 
-    for DIR_NAME in `ls -d */`
+    for DIR_NAME in `find . -maxdepth $depth -type d -exec ls -dA "{}" \; | grep -e /`
     do
-        cd ${DIR_NAME}
+        pushd "${DIR_NAME}" > /dev/null
 
-        gitLine $DIR_NAME
+        process-project $DIR_NAME
 
-        cd ..
+        popd > /dev/null
     done
 
     echo $DIVIDER
-    printf "$FOOTER_FORMAT" "Total" "$TOTAL_MODULES" "" "$TOTAL_COMMITS" "$TOTAL_CHANGES"
+    printf "$FOOTER_FORMAT" "Total" "$TOTAL_MODULES" "" "$TOTAL_COMMITS" "$TOTAL_CHANGES" "$TOTAL_LOCAL"
 }
 
+
+# Check git existence
 hash git &> /dev/null
 if [ $? -eq 1 ]; then
-        echo >&2 "git is required but not found"
+        echo >&2 "git is required but was not found"
         exit
 fi
 
 
-new=0
+depth=1
 limit=-1
 
-while getopts l:h opt ; do
+while getopts l:d:h opt ; do
         case "$opt" in
+                d) depth="$OPTARG";;
                 l) limit="$OPTARG";;
                 h) help;;
                 [?]) help;;
